version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/site-available/default
    depends_on:
      - node-app
  node-app:
    build: .
    environment:
      - PORT=3000
      - SESSION_SECRET=asdasasdasasdasd
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
volumes:
  data:
  
