version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/sites-available/default
    depends_on:
      - node-app
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - SESSION_SECRET=asdasasdasasdasd
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
volumes:
  data:
