version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - node-app
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email tranphuchau9a9@gmail.com -d tpbfico.vn --agree-tos
  node-app:
    build: .
    environment:
      - PORT=3000
      - SESSION_SECRET=asdasasdasasdasd
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
volumes:
  data:
  
